title: "Clarke Lab"
description: "How cells learned to stick together"
baseurl: ""
url: "https://clarkelab.com"
repo_url: "https://github.com/NatClarkeLab/NatClarkeLab.github.io"

collections:
  team:
    output: false
    permalink: /team/:name/
  publications:
    output: true
    permalink: /publications/:path/
  research:
    output: false
    permalink: /research/:name/
  resources:
    output: true
    permalink: /resources/:name/

nav:
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: Team
    url: /team/
  - title: News
    url: /year-archive/
  - title: Resources
    url: /resources/
  - title: Join
    url: /join/
  - title: Contact
    url: /contact/

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
permalink: pretty
